packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@hono/node-server@2.0.12"
